# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoMap

  # Firebase
  pod 'RxFirebase/Auth'
  pod 'RxFirebase/Database'
  pod 'RxFirebase/Storage'
  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'
  pod 'CodableFirebase'
  pod 'GeoFire'
  
  # Reative
  pod 'RxSwift'
  pod 'RxCocoa'
  pod "RxMKMapView"
  pod 'RxDataSources'

  # Keyboard
  pod 'IQKeyboardManagerSwift'

  # TextField
  pod 'SkyFloatingLabelTextField'

  # image downloading
  pod 'Kingfisher'

  # image viewer
  pod 'ImageScrollView'

  # progress indicator
  pod 'UICircularProgressRing'
end
