# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhotoMap

  # Firebase
  pod 'Firebase/Auth'
  pod 'FirebaseUI'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  # Reative
  pod 'RxSwift'
  pod 'RxCocoa'
  pod "RxMKMapView"
end
